Kitapci/Kitapci/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Kitapci.Models;

namespace Kitapci.Controllers
{
    public class BlogController : Controller
    {
        //
        // GET: /Blog/

        public ActionResult Index()
        {
            KitapciDBEntities kitapContext = new KitapciDBEntities();
            IEnumerable<tbl_blog> sorgu = from x in kitapContext.tbl_blog select x;
          
            return View(sorgu);
        }

        public ActionResult BlogDetay(string id)
        {
            KitapciDBEntities kitapContext = new KitapciDBEntities();
            var blogdetay = kitapContext.tbl_blog;
            int intid = Convert.ToInt32(id);
            var blog_detayi = (from b in blogdetay where b.ID == intid select b).SingleOrDefault();
            return View(blog_detayi);
        }

    }
}

Kitapci/Kitapci/Views/Blog/BlogDetay.cshtml
@using Kitapci.Models

@{
    ViewBag.Title = "BlogDetay";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>BlogDetay</h2>

    <div class="content">
        <div class="breadcrumb-inner">
            <div class="container">
                <div class="row">
                    <ul class="breadcrumb text-center light-bg">
                        <li><a href="index.php?page=home">Home</a></li>
                        <li class="active">Blog</li>
                    </ul><!-- /.breadcrumb -->
                </div><!-- /.row -->
                <div class="divider">
                    <img class="img-responsive" src="~/Content/images/blog/@Model.Image" alt="" pagespeed_url_hash="256750320" data-pagespeed-onload="pagespeed.CriticalImages.checkImageForCriticality(this);" pagespeed_lsc_url="http://demo2.transvelo.in/html/bookshop/assets/images/blog/shadow.png" onload="var elem=this;if (this==window) elem=document.body;elem.setAttribute('data-pagespeed-loaded', 1)">
                </div><!-- /.divider -->
            </div><!-- /.container -->
        </div><!-- /.breadcrumb-inner -->
        <div class='container wow fadeInUp'>
            <div class="row inner-top-xs">
                <div class='col-md-9 post'>
                    <div class="post-entry">
                        <div class="row">
                            <div class="col-md-10 center-block">
                                <div class="post-heading">
                                    <h1 class="post-title">Cras dapibus. Vivamus elementum semper nisi. Aenean vulputate eleifend tellus.</h1>
                                    <ul class="clearfix meta">
                                        <li class="author"><a href="#">Hezy Theme</a></li>
                                        <li class="date">12 Jul,2015</li>
                                        <li class="comment">42 comments</li>
                                    </ul><!-- /.meta -->
                                </div><!-- /.post-heading -->
                            </div><!-- /.col -->
                        </div><!-- /.row -->
                        <div class="post-image inner-top-xs">
                            <img class="img-responsive" src="assets/images/blank.gif" data-echo="assets/images/blog/post1.jpg" alt="" pagespeed_url_hash="1623914342" data-pagespeed-onload="pagespeed.CriticalImages.checkImageForCriticality(this);" pagespeed_lsc_url="http://demo2.transvelo.in/html/bookshop/assets/images/blank.gif" onload="var elem=this;if (this==window) elem=document.body;elem.setAttribute('data-pagespeed-loaded', 1)">
                        </div><!-- /.post-image -->
                        <div class="row">
                            <div class='col-md-10 center-block'>
                                <div class="post-content">
                                    <!-- .blog post summary -->
                                    <p class="meta-info m-t-20">Keith Haring,NYC,5/82</p>
                                    <h2 class="post-content-heading">@Model.Title</h2>
                                    <p class="post-text m-t-20">
                                       @Model.Article
                                    </p>
                                   
                                    
                                    
                                    
                                    
                                    <div class="row">
                                        <div class="col-md-12">
                                            <p class="text">tattooed cray carles. Keffiyeh pour-over church-key ennui ethnic fanny pack. Bicycle rights high life twee american apparel. Locavore sartorial neutra pug terry richardson, brunch mustache seitan. Intelligentsia disrupt food truck blog, wolf whatever messenger bag ethical brunch high life four loko. Fixie godard cosby sweater, swag blog marfa american apparel quinoa wes anderson viral actually carles. Vegan disrupt mustache, kale chips fap chillwave neutra iphone blog sustainable terry richardson cred single-origin coffee.</p>
                                            <p class="text">Fingerstache pug skateboard, pop-up quinoa typewriter seitan disrupt meggings pickled Austin pinterest try-hard art party keffiyeh. Street art Austin VHS artisan bushwick. Locavore sartorial neutra pug terry richardson, brunch mustache seitan. Intelligentsia disrupt food truck blog, wolf whatever messenger bag ethical brunch high life four loko. Fixie godard cosby sweater, swag blog marfa american apparel quinoa wes anderson viral actually carles. Vegan disrupt mustache, kale chips fap chillwave neutra iphone blog sustainable terry richardson cred single-origin coffee.</p>
                                            <h5 class="austin-irony inner-top-vs">H4 Austin irony bespoke, you probably haven't heard of them </h5>
                                            <ul class="notes m-t-20">
                                                <li>Fashion axe church-key wes anderson kale chips four loko.</li>
                                                <li>Brooklyn blog synth whatever. </li>
                                                <li>Gluten-free quinoa selfies carles, kogi gentrify retro marfa viral.</li>
                                                <li>Odd future photo booth flannel ethnic pug, occupy keffiyeh synth blue bottle tofu tonx iphone. </li>
                                                <li>Blue bottle 90's vice trust fund gastropub.</li>
                                                <li>
                                                    Austin mlkshk carles selvage fixie ennui. Irony plaid deep v vegan carles small batch thundercats
                                                    aesthetic.
                                                    Semiotics lo-fi me
                                                </li>
                                                <li>Semiotics lo-fi meh dreamcatcher, vice truffaut 90's retro.</li>
                                            </ul>
                                            <div class='lined-paper-content inner-top-50'>
                                                <div class="paper">
                                                    <div class="tape"></div>
                                                    <div class="head"></div>
                                                    <div class="row review-content">
                                                        <blockquote>
                                                            <p class="inner-left-md">Odd future photo booth flannel ethnic paug, occupy keffiyeh synth blue bottle tofu tonx iphone. Blue bottle 90's vice trust fund gastropub. Austin mlkshk carles selvage fixie ennui. Irony plaid deep v vegan carles small batch thundercats aesthetic. Semiotics lo-fi meh dreamcatcher, vice truffaut 90's retro.</p>
                                                        </blockquote>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="divider inner-top-50">
                                                <img class="img-responsive" src="assets/images/shadows/blog-post-shadow.png" alt="" pagespeed_url_hash="3123779561" data-pagespeed-onload="pagespeed.CriticalImages.checkImageForCriticality(this);" pagespeed_lsc_url="http://demo2.transvelo.in/html/bookshop/assets/images/shadows/blog-post-shadow.png" onload="var elem=this;if (this==window) elem=document.body;elem.setAttribute('data-pagespeed-loaded', 1)">
                                            </div><!-- /.divider -->
                                            <ul class="mbt-pager clearfix">
                                                <li class="next">
                                                    <a href="#">Levi x Nike SB 511 Stateboarding</a>
                                                    <i class="fa fa-chevron-left"></i>
                                                </li>
                                                <li class="previous">
                                                    <i class="fa fa-chevron-right"></i>
                                                    <a href="#">Emerica Laced High GT.</a>
                                                </li>
                                            </ul>
                                        </div>
                                    </div>
                                    <!-- /.blog post summary -->
                                    <!-- .blog post comment -->
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
                                    

Kitapci/Kitapci/Views/Blog/Index.cshtml
@using Kitapci.Models
@model IEnumerable<Kitapci.Models.tbl_blog>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div class="content">
<div class="breadcrumb-inner light-bg">
<div class="container">
<div class="row">
<ul class="breadcrumb text-center light-bg">
<li><a href="index.php?page=home">Home</a></li>
<li class="active">Blog</li>
</ul><!-- /.breadcrumb -->
</div><!-- /.row -->
<div class="divider">
<img class="img-responsive" src="/Content/images/blog/shadow.png.pagespeed.ce.z1swr10_K4.png" alt="" 256750320" data-pagespeed-onload="pagespeed.CriticalImages.checkImageForCriticality(this);" onload="var elem=this;if (this==window) elem=document.body;elem.setAttribute('data-pagespeed-loaded', 1)">
</div><!-- /.divider -->
</div><!-- /.container -->
</div><!-- /.breadcrumb-inner -->
<div class='container'>
<div class="row inner-top-xs">
<div class='col-md-9'>
<!-- .blog post -->


    @foreach (tbl_blog item in Model)
    {
        
  
<div class="blog-post wow fadeInUp animated outer-bottom-sm">
<a href="/Blog/Blog-Post/@item.ID" class="blog-image"><img alt="" src="~/Content/images/blog/@item.Image" class="img-responsive"></a>
<div class="row">
<div class="col-md-9 center-block">
<div class="blog-info">
<h2 class="blog-title"> @Html.ActionLink(item.Title,"BlogDetay","Blog",new {id=item.ID},null)</h2>
<ul class="clearfix meta">
<li class="author"><a href="#">Hezy Theme</a></li>
<li class="date">@item.Date</li>
<li class="comment">42 comments</li>
</ul><!-- /.meta -->
<p class="m-t-20 blog-text">@item.Article
<a class="continue-reading" href="#">Continue Reading &rarr;</a></p>
</div><!-- /.blog-info -->
</div>
</div>
</div><!-- /.blog-post -->
  }


	<!-- /.blog post -->
</div><!-- /.col -->
<div class='col-md-3'>
<!-- .blog sidebar -->
<!-- ============================================== BLOG SIDEBAR ============================================== -->
<aside class="sidebar blog-sidebar">
<div class="widget clearfix outer-bottom-xs">
<h4 class="blog-sidebar-title">Social</h4>
<div class="body m-t-20">
<ul class="clearfix list-unstyled sidebar-social-contact list-inline">
<li><a href="#" class="fa fa-facebook" title="Facebook"></a></li>
<li><a href="#" class="fa fa-pinterest" title="Pinterest"></a></li>
<li><a href="#" class="fa fa-linkedin" title="linkedin"></a></li>
<li><a href="#" class="fa fa-twitter" title="Twitter"></a></li>
<li><a href="#" class="fa fa-google-plus" title="Google Plus"></a></li>
<li><a href="#" class="fa fa-rss" title="Rss"></a></li>
<li><a href="#" class="fa fa-facebook" title="Facebook"></a></li>
</ul><!-- /.list-unstyled -->
</div><!-- /.body -->
</div><!-- /.widget -->
 
      @Html.Action("PopularPosts","Shared")

<div class="widget clearfix outer-bottom-xs">
<h4 class="blog-sidebar-title">Text Widget</h4>
<div class="body m-t-20">
<p><span class="black-box"></span>A cras tincidunt, ut tellus et. Gravida scele risque, ipsum sed iacul is, nunc non namtellus.purus purus elit. Cras ante eros. Erat vel. Donec vestibulum sed, vel euismod donec. </p>
</div><!-- /.body -->
</div><!-- /.widget -->
<div class="widget clearfix outer-bottom-xs">
<h4 class="blog-sidebar-title">Meta</h4>
<div class="body m-t-20">
<ul class="clearfix list-unstyled category-list">
<li><a href="#">Site Admin</a></li>
<li><a href="#">Log Out</a> </li>
<li><a href="#">Enteries RSS</a></li>
<li><a href="#">Comments RSS</a></li>
<li><a href="#">Wordpress.org</a></li>
</ul><!-- /.list-unstyled -->
</div><!-- /.body -->
</div><!-- /.widget -->
<div class="widget clearfix outer-bottom-xs">
<h4 class="blog-sidebar-title">Categories</h4>
<div class="body m-t-20">
<ul class="clearfix list-unstyled category-list">
<li class="sub-menu"><a class="dropdown-toggle" data-toggle="dropdown" href="#">New Enteries (38)</a>
<ul>
<li><a href="#">Cotton Sweat (15)</a></li>
<li><a href="#">Trends (22)</a></li>
</ul>
</li>
<li><a href="#">Women Fashion (13)</a></li>
<li><a href="#">Hollywood Style (15)</a></li>
<li><a href="#">90's (6)</a></li>
<li><a href="#">Regular Fit (32)</a></li>
</ul><!-- /.list-unstyled -->
</div><!-- /.body -->
</div><!-- /.widget -->
</aside><!-- /.sidebar -->
<!-- ============================================== BLOG SIDEBAR : END ============================================== -->	<!-- /.blog sidebar -->
</div>
</div><!-- /.container -->
</div><!-- /.row -->
</div><!-- /.content --> <!-- ============================================== FOOTER ============================================== -->